WITH ROW_LISTINGS AS(
    SELECT * FROM AIRBNB.RAW.RAW_LISTINGS
)
select
    ID as LISTING_ID,
    LISTING_URL ,
    NAME as LISTING_NAME,
    ROOM_TYPE ,
    MINIMUM_NIGHTS ,
    HOST_ID ,
    PRICE as PRICE_STR,
    CREATED_AT ,
    UPDATED_AT
    from ROW_LISTINGS